const jobs = [
	{
		id: 1,
		title: "Product UI Designer",
		company: "Google",
		logo: "https://logo.clearbit.com/google.com",
		location: "Bandung",
		type: "Full-Time",
		isUrgent: false,
		salary: "$1000-$4000",
		duration: "3-12 month",
		applied: 12,
		rating: 4.5,
		postedAgo: "4 days ago",
		description:
			"Looking for an experienced UI designer for an ongoing project. You will work with the existing team to develop new features.",
		tags: ["User Interface Design", "Figma", "Designer"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 2,
		title: "Product UI Designer",
		company: "Spotify",
		logo: "https://logo.clearbit.com/spotify.com",
		location: "Tangerang",
		type: "Remote",
		isUrgent: false,
		salary: "$800-$3000",
		duration: "1-6 month",
		applied: 45,
		rating: 4.5,
		postedAgo: "1 days ago",
		description:
			"We are looking for a creative UI designer to join our remote team and help shape the future of music experience.",
		tags: ["UI Design", "Figma", "Prototyping"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 3,
		title: "House Keeping",
		company: "AirBNB",
		logo: "https://logo.clearbit.com/airbnb.com",
		location: "Sukabumi",
		type: "Full-Time",
		isUrgent: true,
		salary: "$500-$1500",
		duration: "Permanent",
		applied: 64,
		rating: 4.5,
		postedAgo: "3 days ago",
		description:
			"Urgent need for housekeeping staff to maintain our properties to the highest standard.",
		tags: ["Cleaning", "Hospitality", "Full-Time"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 4,
		title: "UX Designer",
		company: "PT. Beruang Motors",
		logo: "https://via.placeholder.com/40",
		location: "Bandung",
		type: "Full-Time",
		isUrgent: true,
		salary: "$1000-$4000",
		duration: "3-12 month",
		applied: 45,
		rating: 4.0,
		postedAgo: "1 days ago",
		description:
			"Looking for an experienced UX designer for an ongoing project. It is hoped that you will be able to work with the existing team on the project we are currently developing.",
		tags: ["User Interface Design", "Figma", "Designer", "Working"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 5,
		title: "Frontend Developer",
		company: "Fox Sin",
		logo: "https://via.placeholder.com/40",
		location: "Jakarta",
		type: "Remote",
		isUrgent: false,
		salary: "$1000-$4000",
		duration: "3-12 month",
		applied: 30,
		rating: 4.2,
		postedAgo: "2 days ago",
		description:
			"We need a skilled frontend developer who can build responsive and performant web applications.",
		tags: ["React", "JavaScript", "CSS"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 6,
		title: "Graphic Designer",
		company: "Meta",
		logo: "https://logo.clearbit.com/meta.com",
		location: "Islamabad",
		type: "Remote",
		isUrgent: false,
		salary: "$700-$2000",
		duration: "6 month",
		applied: 20,
		rating: 4.3,
		postedAgo: "5 days ago",
		description:
			"Join our creative team to design stunning visuals for our global campaigns.",
		tags: ["Photoshop", "Illustrator", "Branding"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 7,
		title: "UX Writer",
		company: "Netflix",
		logo: "https://logo.clearbit.com/netflix.com",
		location: "Surabaya",
		type: "Full-Time",
		isUrgent: false,
		salary: "$900-$3000",
		duration: "Permanent",
		applied: 18,
		rating: 4.7,
		postedAgo: "6 days ago",
		description:
			"Help craft the words that make our product experience clear, helpful, and human.",
		tags: ["Writing", "UX", "Content"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 8,
		title: "React Developer",
		company: "Tokopedia",
		logo: "https://logo.clearbit.com/tokopedia.com",
		location: "Jakarta",
		type: "Full-Time",
		isUrgent: true,
		salary: "$1200-$5000",
		duration: "Permanent",
		applied: 55,
		rating: 4.6,
		postedAgo: "1 days ago",
		description:
			"We are urgently looking for a React developer to join our growing engineering team.",
		tags: ["React", "TypeScript", "Node.js"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 9,
		title: "Senior Frontend Developer",
		company: "Microsoft",
		logo: "https://logo.clearbit.com/microsoft.com",
		location: "Singapore",
		type: "Remote",
		isUrgent: true,
		salary: "$3000-$7000",
		duration: "Permanent",
		applied: 70,
		rating: 4.8,
		postedAgo: "2 days ago",
		description:
			"We are looking for an experienced frontend developer who can build scalable and modern web applications using React and TypeScript.",
		tags: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 10,
		title: "Frontend Engineer",
		company: "Adobe",
		logo: "https://logo.clearbit.com/adobe.com",
		location: "Karachi",
		type: "Full-Time",
		isUrgent: false,
		salary: "$2500-$6000",
		duration: "Permanent",
		applied: 40,
		rating: 4.6,
		postedAgo: "5 days ago",
		description:
			"Join our frontend engineering team to create high-performance and accessible user interfaces for millions of users.",
		tags: ["JavaScript", "React", "Accessibility", "CSS"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 11,
		title: "React Frontend Developer",
		company: "Vercel",
		logo: "https://logo.clearbit.com/vercel.com",
		location: "Jakarta",
		type: "Remote",
		isUrgent: true,
		salary: "$2000-$5500",
		duration: "6-12 month",
		applied: 28,
		rating: 4.9,
		postedAgo: "1 day ago",
		description:
			"We are hiring a React frontend developer with experience in building responsive and interactive web applications.",
		tags: ["React", "Next.js", "Tailwind CSS", "Frontend"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 12,
		title: "Junior Frontend Developer",
		company: "Shopify",
		logo: "https://logo.clearbit.com/shopify.com",
		location: "Bandung",
		type: "Full-Time",
		isUrgent: false,
		salary: "$1000-$2500",
		duration: "Permanent",
		applied: 22,
		rating: 4.4,
		postedAgo: "3 days ago",
		description:
			"Great opportunity for a frontend developer who understands React basics and wants to grow in a fast-paced environment.",
		tags: ["HTML", "CSS", "JavaScript", "React"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 13,
		title: "Backend Engineer",
		company: "Amazon",
		logo: "https://logo.clearbit.com/amazon.com",
		location: "Seattle",
		type: "Full-Time",
		isUrgent: true,
		salary: "$4000-$9000",
		duration: "Permanent",
		applied: 102,
		rating: 4.7,
		postedAgo: "2 days ago",
		description:
			"Design and implement scalable microservices using Java and AWS.",
		tags: ["Java", "AWS", "Backend"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 14,
		title: "Product Manager",
		company: "Slack",
		logo: "https://logo.clearbit.com/slack.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$3500-$8000",
		duration: "Permanent",
		applied: 85,
		rating: 4.8,
		postedAgo: "1 week ago",
		description:
			"Lead the development of new communication features for millions of users.",
		tags: ["Product", "Management", "Agile"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 15,
		title: "Data Scientist",
		company: "Tesla",
		logo: "https://logo.clearbit.com/tesla.com",
		location: "Palo Alto",
		type: "Full-Time",
		isUrgent: true,
		salary: "$5000-$10000",
		duration: "Permanent",
		applied: 150,
		rating: 4.9,
		postedAgo: "12 hours ago",
		description:
			"Work on cutting-edge AI and machine learning models for autonomous driving.",
		tags: ["Python", "Machine Learning", "AI"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 16,
		title: "Mobile App Developer",
		company: "Instagram",
		logo: "https://logo.clearbit.com/instagram.com",
		location: "Menlo Park",
		type: "Full-Time",
		isUrgent: false,
		salary: "$3000-$7500",
		duration: "Permanent",
		applied: 60,
		rating: 4.6,
		postedAgo: "3 days ago",
		description:
			"Develop high-quality features for the world's most popular photo-sharing app.",
		tags: ["React Native", "iOS", "Android"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 17,
		title: "Security Engineer",
		company: "Cloudflare",
		logo: "https://logo.clearbit.com/cloudflare.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: true,
		salary: "$4500-$9500",
		duration: "Permanent",
		applied: 35,
		rating: 4.7,
		postedAgo: "4 days ago",
		description:
			"Help protect the global internet infrastructure from cyber threats.",
		tags: ["Security", "Network", "Rust"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 18,
		title: "DevOps Architect",
		company: "DigitalOcean",
		logo: "https://logo.clearbit.com/digitalocean.com",
		location: "New York",
		type: "Remote",
		isUrgent: false,
		salary: "$4000-$8500",
		duration: "Permanent",
		applied: 48,
		rating: 4.5,
		postedAgo: "6 days ago",
		description: "Optimize our cloud infrastructure and deployment pipelines.",
		tags: ["Kubernetes", "Docker", "Terraform"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 19,
		title: "Blockchain Developer",
		company: "Coinbase",
		logo: "https://logo.clearbit.com/coinbase.com",
		location: "San Francisco",
		type: "Remote",
		isUrgent: true,
		salary: "$5000-$12000",
		duration: "Permanent",
		applied: 90,
		rating: 4.8,
		postedAgo: "2 days ago",
		description: "Build secure and decentralized financial systems.",
		tags: ["Solidity", "Blockchain", "Ethereum"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 20,
		title: "QA Engineer",
		company: "Zoom",
		logo: "https://logo.clearbit.com/zoom.us",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$2000-$4500",
		duration: "Permanent",
		applied: 52,
		rating: 4.4,
		postedAgo: "5 days ago",
		description:
			"Ensure the highest quality of video conferencing experiences.",
		tags: ["Selenium", "Automation", "Testing"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 21,
		title: "Motion Designer",
		company: "TikTok",
		logo: "https://logo.clearbit.com/tiktok.com",
		location: "Los Angeles",
		type: "Full-Time",
		isUrgent: false,
		salary: "$2500-$5500",
		duration: "6-12 month",
		applied: 75,
		rating: 4.5,
		postedAgo: "3 days ago",
		description:
			"Create engaging animations and motion graphics for social media content.",
		tags: ["After Effects", "Motion", "Animation"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 22,
		title: "Golang Backend Developer",
		company: "Uber",
		logo: "https://logo.clearbit.com/uber.com",
		location: "Amsterdam",
		type: "Full-Time",
		isUrgent: true,
		salary: "$4000-$9000",
		duration: "Permanent",
		applied: 40,
		rating: 4.7,
		postedAgo: "1 day ago",
		description:
			"Scalable systems development using Go for high-traffic logistics platforms.",
		tags: ["Go", "Microservices", "Redis"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 23,
		title: "Technical Writer",
		company: "Stripe",
		logo: "https://logo.clearbit.com/stripe.com",
		location: "Dublin",
		type: "Remote",
		isUrgent: false,
		salary: "$2500-$6000",
		duration: "Permanent",
		applied: 30,
		rating: 4.9,
		postedAgo: "1 week ago",
		description:
			"Write world-class documentation for financial APIs and tools.",
		tags: ["Documentation", "API", "Content"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 24,
		title: "Fullstack Developer",
		company: "Airbnb",
		logo: "https://logo.clearbit.com/airbnb.com",
		location: "London",
		type: "Full-Time",
		isUrgent: false,
		salary: "$3500-$7500",
		duration: "Permanent",
		applied: 68,
		rating: 4.6,
		postedAgo: "4 days ago",
		description:
			"Work across the stack to build seamless travel booking experiences.",
		tags: ["React", "Ruby on Rails", "SQL"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 25,
		title: "Data Analyst",
		company: "LinkedIn",
		logo: "https://logo.clearbit.com/linkedin.com",
		location: "Remote",
		type: "Contract",
		isUrgent: false,
		salary: "$2000-$5000",
		duration: "6 month",
		applied: 95,
		rating: 4.5,
		postedAgo: "2 days ago",
		description: "Analyze user engagement data to drive business decisions.",
		tags: ["SQL", "Tableau", "Data"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 26,
		title: "Visual Designer",
		company: "Pinterest",
		logo: "https://logo.clearbit.com/pinterest.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$2500-$5000",
		duration: "Permanent",
		applied: 42,
		rating: 4.7,
		postedAgo: "5 days ago",
		description:
			"Design inspiring visual systems for our creative discovery engine.",
		tags: ["Visual Design", "Adobe Suite", "Creative"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 27,
		title: "Cloud Support Engineer",
		company: "AWS",
		logo: "https://logo.clearbit.com/amazon.com",
		location: "Sydney",
		type: "Full-Time",
		isUrgent: true,
		salary: "$3000-$6500",
		duration: "Permanent",
		applied: 38,
		rating: 4.6,
		postedAgo: "2 days ago",
		description:
			"Assist enterprise customers in troubleshooting cloud infrastructure issues.",
		tags: ["AWS", "Linux", "Support"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 28,
		title: "ML Engineer",
		company: "OpenAI",
		logo: "https://logo.clearbit.com/openai.com",
		location: "San Francisco",
		type: "Full-Time",
		isUrgent: true,
		salary: "$8000-$15000",
		duration: "Permanent",
		applied: 200,
		rating: 5.0,
		postedAgo: "1 hour ago",
		description: "Develop and scale large language models like GPT.",
		tags: ["PyTorch", "NLP", "Scale"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 29,
		title: "Community Manager",
		company: "Discord",
		logo: "https://logo.clearbit.com/discord.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$1500-$4000",
		duration: "Permanent",
		applied: 110,
		rating: 4.8,
		postedAgo: "4 days ago",
		description: "Engage with and grow our developer and gaming communities.",
		tags: ["Community", "Social Media", "Gaming"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 30,
		title: "Site Reliability Engineer",
		company: "GitHub",
		logo: "https://logo.clearbit.com/github.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: true,
		salary: "$4000-$9000",
		duration: "Permanent",
		applied: 44,
		rating: 4.9,
		postedAgo: "3 days ago",
		description:
			"Maintain the availability and performance of the world's largest code host.",
		tags: ["Ruby", "Go", "Infrastructure"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 31,
		title: "Illustrator",
		company: "Medium",
		logo: "https://logo.clearbit.com/medium.com",
		location: "Remote",
		type: "Freelance",
		isUrgent: false,
		salary: "$50-$200/hour",
		duration: "Flexible",
		applied: 15,
		rating: 4.4,
		postedAgo: "1 week ago",
		description:
			"Create unique editorial illustrations for high-profile articles.",
		tags: ["Illustration", "Digital Art", "Editorial"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 32,
		title: "Android Developer",
		company: "Grab",
		logo: "https://logo.clearbit.com/grab.com",
		location: "Jakarta",
		type: "Full-Time",
		isUrgent: true,
		salary: "$1500-$4500",
		duration: "Permanent",
		applied: 58,
		rating: 4.5,
		postedAgo: "2 days ago",
		description:
			"Build features for the leading everyday superapp in Southeast Asia.",
		tags: ["Kotlin", "Android SDK", "Java"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 33,
		title: "Content Strategist",
		company: "Twitter",
		logo: "https://logo.clearbit.com/twitter.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$2500-$5500",
		duration: "Permanent",
		applied: 32,
		rating: 4.2,
		postedAgo: "5 days ago",
		description: "Define the content strategy for our consumer product teams.",
		tags: ["Content Strategy", "Marketing", "Copywriting"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 34,
		title: "Cyber Security Analyst",
		company: "IBM",
		logo: "https://logo.clearbit.com/ibm.com",
		location: "Islamabad",
		type: "Full-Time",
		isUrgent: false,
		salary: "$1200-$3500",
		duration: "Permanent",
		applied: 25,
		rating: 4.3,
		postedAgo: "3 days ago",
		description:
			"Monitor and respond to security threats in enterprise environments.",
		tags: ["Cybersecurity", "SIEM", "Forensics"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 35,
		title: "Interaction Designer",
		company: "Figma",
		logo: "https://logo.clearbit.com/figma.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: true,
		salary: "$4000-$8000",
		duration: "Permanent",
		applied: 88,
		rating: 4.9,
		postedAgo: "1 day ago",
		description: "Design the future of collaborative design tools.",
		tags: ["Interaction", "UI", "Prototyping"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 36,
		title: "Customer Success Lead",
		company: "Salesforce",
		logo: "https://logo.clearbit.com/salesforce.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$3000-$6500",
		duration: "Permanent",
		applied: 40,
		rating: 4.7,
		postedAgo: "4 days ago",
		description:
			"Help our customers maximize value from the Salesforce ecosystem.",
		tags: ["CRM", "Management", "Success"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 37,
		title: "SEO Specialist",
		company: "HubSpot",
		logo: "https://logo.clearbit.com/hubspot.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$1500-$4000",
		duration: "Permanent",
		applied: 50,
		rating: 4.6,
		postedAgo: "6 days ago",
		description:
			"Drive organic traffic growth through advanced SEO strategies.",
		tags: ["SEO", "Marketing", "Analytics"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 38,
		title: "Database Administrator",
		company: "Oracle",
		logo: "https://logo.clearbit.com/oracle.com",
		location: "Austin",
		type: "Full-Time",
		isUrgent: true,
		salary: "$3500-$7500",
		duration: "Permanent",
		applied: 22,
		rating: 4.4,
		postedAgo: "2 days ago",
		description: "Manage and optimize large-scale enterprise databases.",
		tags: ["SQL", "Oracle DB", "NoSQL"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 39,
		title: "Unity Game Developer",
		company: "Electronic Arts",
		logo: "https://logo.clearbit.com/ea.com",
		location: "Remote",
		type: "Contract",
		isUrgent: true,
		salary: "$3000-$6000",
		duration: "12 month",
		applied: 65,
		rating: 4.5,
		postedAgo: "1 day ago",
		description:
			"Develop mechanics and gameplay systems for upcoming mobile titles.",
		tags: ["C#", "Unity", "Game Dev"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 40,
		title: "Social Media Manager",
		company: "Reddit",
		logo: "https://logo.clearbit.com/reddit.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$1800-$4200",
		duration: "Permanent",
		applied: 120,
		rating: 4.6,
		postedAgo: "3 days ago",
		description: "Curate and create viral content for our social platforms.",
		tags: ["Social Media", "Reddit", "Viral"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 41,
		title: "Hardware Engineer",
		company: "Apple",
		logo: "https://logo.clearbit.com/apple.com",
		location: "Cupertino",
		type: "Full-Time",
		isUrgent: true,
		salary: "$6000-$13000",
		duration: "Permanent",
		applied: 92,
		rating: 4.9,
		postedAgo: "5 hours ago",
		description:
			"Work on the next generation of silicon and hardware architecture.",
		tags: ["Hardware", "Circuits", "Silicon"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 42,
		title: "AR/VR Designer",
		company: "Meta",
		logo: "https://logo.clearbit.com/meta.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$3500-$7500",
		duration: "Permanent",
		applied: 40,
		rating: 4.8,
		postedAgo: "4 days ago",
		description: "Design immersive experiences for the metaverse.",
		tags: ["AR", "VR", "Unity"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 43,
		title: "System Administrator",
		company: "Cisco",
		logo: "https://logo.clearbit.com/cisco.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$2500-$5500",
		duration: "Permanent",
		applied: 28,
		rating: 4.4,
		postedAgo: "1 week ago",
		description: "Maintain internal networks and server environments.",
		tags: ["Networking", "Linux", "Windows"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 44,
		title: "Video Editor",
		company: "YouTube",
		logo: "https://logo.clearbit.com/youtube.com",
		location: "San Bruno",
		type: "Contract",
		isUrgent: true,
		salary: "$2000-$5000",
		duration: "3 month",
		applied: 85,
		rating: 4.7,
		postedAgo: "2 days ago",
		description:
			"Edit promotional and educational video content for YouTube Creators.",
		tags: ["Premiere Pro", "Final Cut", "Video"],
		experience: "UX Designer",
		isBookmarked: false,
	},
	{
		id: 45,
		title: "Copywriter",
		company: "Mailchimp",
		logo: "https://logo.clearbit.com/mailchimp.com",
		location: "Remote",
		type: "Freelance",
		isUrgent: false,
		salary: "$40-$100/hour",
		duration: "Ongoing",
		applied: 19,
		rating: 4.6,
		postedAgo: "6 days ago",
		description:
			"Write compelling email marketing copy for a variety of industries.",
		tags: ["Copywriting", "Marketing", "Email"],
		experience: "Developer",
		isBookmarked: false,
	},
	{
		id: 46,
		title: "Shopify Developer",
		company: "Gymshark",
		logo: "https://logo.clearbit.com/gymshark.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: true,
		salary: "$2500-$5500",
		duration: "Permanent",
		applied: 34,
		rating: 4.5,
		postedAgo: "1 day ago",
		description:
			"Customize and optimize our high-traffic e-commerce storefront.",
		tags: ["Liquid", "Shopify", "JavaScript"],
		experience: "UX Writer",
		isBookmarked: false,
	},
	{
		id: 47,
		title: "Data Warehouse Engineer",
		company: "Snowflake",
		logo: "https://logo.clearbit.com/snowflake.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$4500-$9000",
		duration: "Permanent",
		applied: 27,
		rating: 4.9,
		postedAgo: "4 days ago",
		description:
			"Optimize data storage and processing workflows for cloud data warehousing.",
		tags: ["Data Warehouse", "SQL", "Python"],
		experience: "Frontend Developer",
		isBookmarked: false,
	},
	{
		id: 48,
		title: "Growth Hacker",
		company: "Revolut",
		logo: "https://logo.clearbit.com/revolut.com",
		location: "Berlin",
		type: "Full-Time",
		isUrgent: true,
		salary: "$3000-$7000",
		duration: "Permanent",
		applied: 52,
		rating: 4.7,
		postedAgo: "2 days ago",
		description:
			"Identify and implement creative strategies to drive user acquisition.",
		tags: ["Growth", "Marketing", "A/B Testing"],
		experience: "Graphic Designer",
		isBookmarked: false,
	},
	{
		id: 49,
		title: "Embedded Systems Engineer",
		company: "Nvidia",
		logo: "https://logo.clearbit.com/nvidia.com",
		location: "Remote",
		type: "Full-Time",
		isUrgent: false,
		salary: "$5000-$11000",
		duration: "Permanent",
		applied: 60,
		rating: 4.8,
		postedAgo: "5 days ago",
		description: "Develop firmware for high-performance GPU and AI systems.",
		tags: ["C++", "Firmware", "Hardware"],
		experience: "UI Designer",
		isBookmarked: false,
	},
	{
		id: 50,
		title: "Brand Designer",
		company: "Coca-Cola",
		logo: "https://logo.clearbit.com/coca-cola.com",
		location: "Atlanta",
		type: "Full-Time",
		isUrgent: false,
		salary: "$2500-$6000",
		duration: "Permanent",
		applied: 115,
		rating: 4.5,
		postedAgo: "1 week ago",
		description: "Maintain and evolve the visual identity of a global brand.",
		tags: ["Branding", "Visual Design", "Design Strategy"],
		experience: "UX Designer",
		isBookmarked: false,
	},
];

export default jobs;
